using System.Security.Cryptography;
using System.Text;

namespace CNCGCodeGenerator.Core;

internal static class Planner
{
    public static MotionPlan Plan(GrindingRequest request)
    {
        var start = request.StartPositionMm ?? throw new ValidationException("Input", "StartPositionMm", "Start X, Y and Z coordinates are required.");
        if (request.CoordinateMode != CoordinateMode.Absolute) throw new ValidationException("Input", "CoordinateMode", "This machine uses fixed absolute G90 output.");
        if (request.CoolantEnabled || request.DressingEnabled) throw new ValidationException("Unknown machine data", "Coolant/dressing", "These machine-specific commands are disabled until confirmed.");
        TextValidation.ProgramName(request.ProgramName); TextValidation.Comment(request.ProgramComment, "ProgramComment");
        if (request.TableTravelXMm <= 0 || request.CrossTravelZMm < 0 || (request.CrossTravelZMm > 0 && request.CrossStepZMm <= 0) || request.VerticalDownfeedYPerRoughSweepMm < 0 || request.RoughingSweeps < 0 || request.FinishingSweeps < 0 || request.SparkOutRoundTrips < 0 || (long)request.RoughingSweeps + request.FinishingSweeps <= 0) throw new ValidationException("Input", "Geometry/pass counts", "Require positive X travel, nonnegative coverage/downfeed/counts, and at least one sweep.");
        if (request.SpindleRpm <= 0 || request.XGrindingFeedMmPerMinute <= 0 || (request.VerticalDownfeedYPerRoughSweepMm > 0 && request.YDownfeedMmPerMinute <= 0) || (request.CrossTravelZMm > 0 && request.ZCrossFeedMmPerMinute <= 0)) throw new ValidationException("Input", "Feeds/Rpm", "Required feeds and spindle speed must be positive.");
        foreach (var (value, field) in new[] { (request.TableTravelXMm, "X travel"), (request.CrossTravelZMm, "Z coverage"), (request.CrossStepZMm, "Z step"), (request.VerticalDownfeedYPerRoughSweepMm, "Y downfeed"), (request.XGrindingFeedMmPerMinute, "X feed"), (request.YDownfeedMmPerMinute, "Y feed"), (request.ZCrossFeedMmPerMinute, "Z feed"), (request.SpindleRpm, "RPM") }) Numeric.RequirePrecision(value, OutputDefaults.DecimalPlaces, field);
        if (request.RoughingSweeps > 0 && request.VerticalDownfeedYPerRoughSweepMm <= 0) throw new ValidationException("Input", "Y downfeed", "Y downfeed must be greater than zero when roughing is enabled.");
        if (request.RoughingSweeps == 0 && request.VerticalDownfeedYPerRoughSweepMm > 0) throw new ValidationException("Input", "Y downfeed", "Y downfeed must be zero when roughing sweeps are zero.");
        var (fullSteps, remainder) = ExactDecimal.DivideIntoSteps(request.CrossTravelZMm, request.CrossStepZMm == 0 ? 1 : request.CrossStepZMm); var steps = fullSteps + (remainder > 0 ? 1 : 0); var sweepCount = checked(request.RoughingSweeps + request.FinishingSweeps); var count = checked((long)sweepCount * ((long)steps + 1) * 2 + (request.VerticalDownfeedYPerRoughSweepMm > 0 ? request.RoughingSweeps : 0) + 2L * request.SparkOutRoundTrips); if (count > OutputDefaults.MaximumBlocks - 16) throw new ValidationException("Input", "Motion count", "The generated program is too large.");
        var motions = new List<Motion>(); var current = start; var xOther = ExactDecimal.Add(start.X, request.TableTravelXMm * Danobat30106AConfig.XRightSign); var zSign = request.CrossTravelZMm > 0 ? Danobat30106AConfig.ZInitialCrossSign : 0;
        void Move(Axis axis, decimal target, decimal feed) { if (target == current[axis]) return; Numeric.RequirePrecision(ExactDecimal.Subtract(target, current[axis]), OutputDefaults.DecimalPlaces, $"{axis} increment"); current = current.With(axis, target); motions.Add(new(axis, current, feed)); }
        void Stroke() => Move(Axis.X, current.X == start.X ? xOther : start.X, request.XGrindingFeedMmPerMinute);
        for (var sweep = 0; sweep < sweepCount; sweep++) { if (sweep < request.RoughingSweeps && request.VerticalDownfeedYPerRoughSweepMm > 0) Move(Axis.Y, ExactDecimal.Add(current.Y, request.VerticalDownfeedYPerRoughSweepMm * Danobat30106AConfig.YDownSign), request.YDownfeedMmPerMinute); var zStart = current.Z; var sweepSign = sweep % 2 == 0 ? zSign : -zSign; for (var row = 0; row <= steps; row++) { Stroke(); Stroke(); if (row == steps) break; var coverage = row < fullSteps ? ExactDecimal.Multiply(row + 1m, request.CrossStepZMm) : request.CrossTravelZMm; Move(Axis.Z, ExactDecimal.Add(zStart, sweepSign * coverage), request.ZCrossFeedMmPerMinute); } }
        for (var cycle = 0; cycle < request.SparkOutRoundTrips; cycle++) { Stroke(); Stroke(); }
        return new(start, motions.AsReadOnly());
    }
}

internal static class FagorPostProcessor
{
    public static string Format(MotionPlan plan, GrindingRequest request)
    { var lines = new List<string> { $"; PROGRAM {request.ProgramName}", $"; GENERATOR {GenerationService.Version}", "; MACHINE DANOBAT RTM-2500 SERIAL 30106A FAGOR 8055M", $"; COMMENT {request.ProgramComment}", "; SETUP", "G71", "G94", "G90", $"S{Numeric.Format(request.SpindleRpm)} M03", "; GRINDING" }; foreach (var motion in plan.Motions) lines.Add($"G01 {motion.Axis}{Numeric.Format(motion.TargetMm[motion.Axis])} F{Numeric.Format(motion.FeedMmPerMinute)}"); lines.AddRange(["; SHUTDOWN", "M05", "G90", "M30"]); var text = string.Join("\n", lines) + "\n"; if (lines.Count > OutputDefaults.MaximumBlocks || lines.Any(line => line.Length > OutputDefaults.MaximumBlockLength) || Encoding.ASCII.GetByteCount(text) > OutputDefaults.MaximumFileBytes) throw new ValidationException("Calculation", "Output", "Generated program exceeds internal output capacity."); return text; }
}

public sealed record SimulationResult(IReadOnlyList<Motion> Motions, AxisPosition FinalMm, CoordinateMode FinalMode, bool SpindleRequested, decimal RequestedRpm);
public static class FagorParserSimulator
{
    public static SimulationResult Parse(string text, AxisPosition start)
    { var current = start; var motions = new List<Motion>(); var mode = CoordinateMode.Absolute; var spindle = false; var stopped = false; var ended = false; decimal rpm = 0; var setup = false; foreach (var raw in text.Replace("\r\n", "\n").Split('\n')) { var line = raw.Trim(); if (line.Length == 0 || line.StartsWith(';')) continue; if (ended) Fail("Executable block after M30."); var words = line.Split(' ', StringSplitOptions.RemoveEmptyEntries); if (line is "G71" or "G94") { setup = true; continue; } if (line == "G90") { mode = CoordinateMode.Absolute; continue; } if (line == "M05") { spindle = false; stopped = true; continue; } if (line == "M30") { if (!setup || !stopped || spindle || mode != CoordinateMode.Absolute) Fail("Incomplete setup or shutdown state."); ended = true; continue; } if (words.Length == 2 && words[0].StartsWith('S') && words[1] == "M03") { rpm = Number(words[0][1..]); if (rpm <= 0) Fail("Invalid RPM."); spindle = true; stopped = false; continue; } if (words.Length == 3 && words[0] == "G01" && "XYZ".Contains(words[1][0]) && words[2].StartsWith('F')) { if (!setup || !spindle || stopped) Fail("Invalid motion state."); var axis = Enum.Parse<Axis>(words[1][0].ToString()); var target = Number(words[1][1..]); var feed = Number(words[2][1..]); if (feed <= 0 || target == current[axis]) Fail("Invalid motion."); current = current.With(axis, target); motions.Add(new(axis, current, feed)); continue; } Fail("Unsupported executable block."); } if (!ended || motions.Count == 0) Fail("Missing M30 or motion."); return new(motions.AsReadOnly(), current, mode, spindle, rpm); decimal Number(string token) { if (!System.Text.RegularExpressions.Regex.IsMatch(token, @"\A-?[0-9]+(?:\.[0-9]+)?\z") || !decimal.TryParse(token, System.Globalization.NumberStyles.AllowLeadingSign | System.Globalization.NumberStyles.AllowDecimalPoint, System.Globalization.CultureInfo.InvariantCulture, out var value) || Numeric.Format(value) != token) Fail("Invalid numeric word."); return value; } void Fail(string message) => throw new ValidationException("Parser", "Program", message); }
}

public sealed class ValidatedProgram
{ public string GCode { get; } public string Report { get; } public string Sha256 { get; } public string FileName { get; } public GrindingRequest Request { get; } public MotionPlan Plan { get; } internal ValidatedProgram(string code, string report, string fileName, GrindingRequest request, MotionPlan plan) { GCode = code; Report = report; FileName = fileName; Request = request; Plan = plan; Sha256 = Convert.ToHexString(SHA256.HashData(Encoding.ASCII.GetBytes(code))); } }

public static class GenerationService
{
    public const string Version = "3.0.0";
    public static ValidatedProgram Generate(GrindingRequest request)
    { try { var plan = Planner.Plan(request); var code = FagorPostProcessor.Format(plan, request); var parsed = FagorParserSimulator.Parse(code, plan.StartMm); if (!parsed.Motions.SequenceEqual(plan.Motions) || parsed.FinalMm != plan.Motions[^1].TargetMm || parsed.FinalMode != CoordinateMode.Absolute || parsed.SpindleRequested || parsed.RequestedRpm != request.SpindleRpm) throw new ValidationException("Calculation", "Round-trip", "Formatted program differs from planned trajectory."); return new(code, Report(plan, request), request.ProgramName + OutputDefaults.Extension, request, plan); } catch (OverflowException) { throw new ValidationException("Calculation", "Numeric range", "Arithmetic exceeded exact decimal capacity; export blocked."); } }
    private static string Report(MotionPlan plan, GrindingRequest request) { var positions = new[] { plan.StartMm }.Concat(plan.Motions.Select(m => m.TargetMm)).ToArray(); var sb = new StringBuilder(); sb.AppendLine("Validation passed for configured inputs. Operator review required."); sb.AppendLine("Machine interlocks and physical setup are outside software simulation."); sb.AppendLine("Danobat RTM-2500 / 30106A / Fagor 8055M"); sb.AppendLine("Absolute G90; physical first X direction: RIGHT; commanded first direction: X-."); sb.AppendLine($"Start: X {Numeric.Format(plan.StartMm.X)}, Y {Numeric.Format(plan.StartMm.Y)}, Z {Numeric.Format(plan.StartMm.Z)} mm"); sb.AppendLine($"X stroke: {Numeric.Format(request.TableTravelXMm)} mm; Z coverage: {Numeric.Format(request.CrossTravelZMm)} mm; Z step: {Numeric.Format(request.CrossStepZMm)} mm"); sb.AppendLine($"Roughing sweeps: {request.RoughingSweeps}; finishing sweeps: {request.FinishingSweeps}; total roughing Y downfeed: {Numeric.Format(request.VerticalDownfeedYPerRoughSweepMm * request.RoughingSweeps)} mm"); sb.AppendLine($"Spindle: {Numeric.Format(request.SpindleRpm)} rpm; X feed: {Numeric.Format(request.XGrindingFeedMmPerMinute)}; Y feed: {Numeric.Format(request.YDownfeedMmPerMinute)}; Z feed: {Numeric.Format(request.ZCrossFeedMmPerMinute)} mm/min"); sb.AppendLine($"Estimated X round trips: {plan.Motions.Count(m => m.Axis == Axis.X) / 2}; Z steps: {plan.Motions.Count(m => m.Axis == Axis.Z)}"); foreach (var axis in new[] { Axis.X, Axis.Y, Axis.Z }) sb.AppendLine($"{axis}: min {Numeric.Format(positions.Min(p => p[axis]))}; max {Numeric.Format(positions.Max(p => p[axis]))}; final {Numeric.Format(positions[^1][axis])} mm"); sb.AppendLine("Coolant: disabled. Dresser/V axis: disabled. Review every block before machine use."); return sb.ToString(); }
}
